name: 'dbt_sf'
version: '1.0.0'

profile: 'dbt_sf'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: [">=1.11.0", "<2.0.0"]

models:
  dbt_sf:
    +materialized: table
    staging:
      +materialized: table
      +schema: crm_staging
    marts:
      +materialized: table
      +schema: crm_mart
